#Because GT data is generated by a sampling process, I pulled 5 versions of each GT time series
#and take the average to get more reliable estimates

#load all versions of data
#germany
gt_data_germany1 <- readRDS("Data/GT_Data/germany/gt_data_germany1.RDS")
gt_data_germany2 <- readRDS("Data/GT_Data/germany/gt_data_germany2.RDS")
gt_data_germany3 <- readRDS("Data/GT_Data/germany/gt_data_germany3.RDS")
gt_data_germany4 <- readRDS("Data/GT_Data/germany/gt_data_germany4.RDS")
gt_data_germany5 <- readRDS("Data/GT_Data/germany/gt_data_germany5.RDS")

#international
gt_data_international1 <- readRDS("Data/GT_Data/international/gt_data_international1.RDS")
gt_data_international2 <- readRDS("Data/GT_Data/international/gt_data_international2.RDS")
gt_data_international3 <- readRDS("Data/GT_Data/international/gt_data_international3.RDS")
gt_data_international4 <- readRDS("Data/GT_Data/international/gt_data_international4.RDS")
gt_data_international5 <- readRDS("Data/GT_Data/international/gt_data_international5.RDS")

#calculate final versions of gt data by taking averages
gt_data_germany_final <- gt_data_germany1 #initialise
gt_data_international_final <- gt_data_international1 #initialise
for(i in 1:ncol(gt_data_germany_final)){
  gt_data_germany_final[,i] <- (gt_data_germany1[,i] + gt_data_germany2[,i] + gt_data_germany3[,i]
                                + gt_data_germany4[,i] + gt_data_germany5[,i]) / 5
  gt_data_international_final[,i] <- (gt_data_international1[,i] + gt_data_international2[,i] + gt_data_international3[,i]
                                + gt_data_international4[,i] + gt_data_international5[,i]) / 5
}

#visual check
for(i in 1:50){
  plot(gt_data_international_final[,i])
}

#save final data
saveRDS(gt_data_germany_final,"Data/GT_Data/germany/gt_data_germany_final.RDS")
saveRDS(gt_data_international_final,"Data/GT_Data/germany/gt_data_international_final.RDS")


